name: flutter_grid_button
description: Flutter widget that arrange buttons in a grid. It is useful for making a number pad, calculator, and so on.
version: 1.1.7
homepage: https://github.com/zuvola/flutter_grid_button

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
