name: flutter_grid_button
description: Flutter widget that arrange buttons in a grid.
version: 0.0.1
author: zuvola <zuvola@gmail.com>
homepage: http://www.zuvola.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
